export { evaluateProposalAwaiting } from './proposalAwaiting'
export { evaluateExecutionNotConfirmed } from './executionNotConfirmed'
export { evaluateIdeaNotSimulated } from './ideaNotSimulated'
export { evaluateOverdueDeliverable } from './overdueDeliverable'
export { evaluateRatingNoFollowup } from './ratingNoFollowup'
export { evaluateHighExpectedReturn } from './highExpectedReturn'
export { evaluateThesisStale } from './thesisStale'
