/**
 * Trade Sheet Panel — Snapshot list for Trade Lab.
 *
 * Snapshots are saved simulation states. They are documentation/reference artifacts
 * that can be loaded back into Trade Lab to continue working. They do NOT commit
 * trades or gate execution.
 */

import React, { useState } from 'react'
import { FileText, Inbox, ChevronDown, ChevronRight, CheckCircle2, FileCheck, RotateCcw, Pencil, X, Send } from 'lucide-react'
import { clsx } from 'clsx'
import { format, formatDistanceToNow } from 'date-fns'
import { supabase } from '../../lib/supabase'
import type { TradeSheet, IntentVariant } from '../../types/trading'

interface TradeSheetPanelProps {
  tradeSheets: TradeSheet[]
  assetSymbolMap?: Record<string, string>
  onLoadSnapshot?: (sheet: TradeSheet) => void
  onShareSnapshot?: (sheet: TradeSheet) => void
  isLoadingSnapshot?: boolean
  className?: string
}

const ACTION_COLORS: Record<string, string> = {
  buy: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400',
  add: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400',
  sell: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
  trim: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
}

/** Parse auto-generated snapshot name to extract a clean date display */
function parseSnapshotDisplay(name: string): { label: string; isAutoGenerated: boolean } {
  // Auto-generated names look like "Snapshot — Mar 20, 2026 16:22"
  const match = name.match(/^Snapshot\s*[—–-]\s*(.+)$/)
  if (match) {
    return { label: match[1], isAutoGenerated: true }
  }
  return { label: name, isAutoGenerated: false }
}

function TradeRow({ variant, symbol }: { variant: IntentVariant; symbol: string }) {
  const c = variant.computed
  const hasProposal = !!(variant as any).proposal_id
  return (
    <tr className="border-b border-gray-100 dark:border-gray-800 last:border-b-0">
      <td className="py-1.5 pr-3">
        <span className={clsx(
          'inline-block px-1.5 py-0.5 text-[10px] font-semibold uppercase rounded',
          ACTION_COLORS[variant.action] || 'bg-gray-100 text-gray-600'
        )}>
          {variant.action}
        </span>
      </td>
      <td className="py-1.5 pr-3 text-[13px] font-medium text-gray-900 dark:text-white">
        <span className="flex items-center gap-1.5">
          {symbol}
          {hasProposal && (
            <FileCheck className="h-3 w-3 text-teal-500 dark:text-teal-400" title="Based on analyst recommendation" />
          )}
        </span>
      </td>
      <td className="py-1.5 pr-3 text-[13px] font-mono text-gray-600 dark:text-gray-300">
        {variant.sizing_input}
      </td>
      <td className="py-1.5 pr-3 text-[13px] font-mono text-right text-gray-600 dark:text-gray-300">
        {c ? `${c.delta_shares > 0 ? '+' : ''}${c.delta_shares.toLocaleString()}` : '—'}
      </td>
      <td className="py-1.5 pr-3 text-[13px] font-mono text-right text-gray-600 dark:text-gray-300">
        {c ? `${c.delta_weight > 0 ? '+' : ''}${c.delta_weight.toFixed(2)}%` : '—'}
      </td>
      <td className="py-1.5 text-[13px] font-mono text-right text-gray-600 dark:text-gray-300">
        {c ? `$${Math.abs(c.notional_value).toLocaleString()}` : '—'}
      </td>
    </tr>
  )
}

function SheetListItem({
  sheet,
  assetSymbolMap,
  onLoadSnapshot,
  onShareSnapshot,
  isLoadingSnapshot,
}: {
  sheet: TradeSheet
  assetSymbolMap: Record<string, string>
  onLoadSnapshot?: (sheet: TradeSheet) => void
  onShareSnapshot?: (sheet: TradeSheet) => void
  isLoadingSnapshot?: boolean
}) {
  const [expanded, setExpanded] = useState(false)
  const [isRenaming, setIsRenaming] = useState(false)
  const [renameValue, setRenameValue] = useState('')
  const [localName, setLocalName] = useState(sheet.name)
  const variants = sheet.variants_snapshot || []

  const recCount = variants.filter((v: any) => v.proposal_id).length
  const { label: displayLabel, isAutoGenerated } = parseSnapshotDisplay(localName)

  const handleStartRename = (e: React.MouseEvent) => {
    e.stopPropagation()
    setRenameValue(isAutoGenerated ? '' : localName)
    setIsRenaming(true)
  }

  const handleSaveRename = async () => {
    const trimmed = renameValue.trim()
    if (!trimmed) { setIsRenaming(false); return }
    setLocalName(trimmed)
    setIsRenaming(false)
    await supabase.from('trade_sheets').update({ name: trimmed }).eq('id', sheet.id)
  }

  // Compact notional formatting
  const fmtNotional = (val: number) => {
    const abs = Math.abs(val)
    if (abs >= 1_000_000) return `$${(abs / 1_000_000).toFixed(1)}M`
    if (abs >= 1_000) return `$${(abs / 1_000).toFixed(0)}K`
    return `$${abs.toFixed(0)}`
  }

  return (
    <div className="rounded-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 overflow-hidden">
      {/* Header */}
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center justify-between px-3 py-2.5 hover:bg-gray-50 dark:hover:bg-gray-700/50 transition-colors text-left"
      >
        <div className="flex items-center gap-2 min-w-0">
          {expanded
            ? <ChevronDown className="w-4 h-4 text-gray-400 flex-shrink-0" />
            : <ChevronRight className="w-4 h-4 text-gray-400 flex-shrink-0" />
          }
          <div className="min-w-0">
            {/* Name or date — primary identity */}
            {isRenaming ? (
              <div className="flex items-center gap-1" onClick={e => e.stopPropagation()}>
                <input
                  type="text"
                  value={renameValue}
                  onChange={e => setRenameValue(e.target.value)}
                  onKeyDown={e => { if (e.key === 'Enter') handleSaveRename(); if (e.key === 'Escape') setIsRenaming(false) }}
                  autoFocus
                  placeholder="Name this snapshot..."
                  className="text-sm font-medium px-1.5 py-0.5 rounded border border-primary-400 dark:border-primary-500 bg-white dark:bg-gray-900 text-gray-900 dark:text-white w-48 focus:outline-none focus:ring-1 focus:ring-primary-400"
                />
                <button onClick={handleSaveRename} className="text-primary-600 dark:text-primary-400 hover:text-primary-700 p-0.5"><CheckCircle2 className="w-3.5 h-3.5" /></button>
                <button onClick={() => setIsRenaming(false)} className="text-gray-400 hover:text-gray-600 p-0.5"><X className="w-3.5 h-3.5" /></button>
              </div>
            ) : (
              <div className="flex items-center gap-1.5 group/name">
                <span className="text-sm font-medium text-gray-900 dark:text-gray-100 truncate">
                  {isAutoGenerated ? displayLabel : localName}
                </span>
                {isAutoGenerated && (
                  <span className="text-[10px] text-gray-400 dark:text-gray-500">Snapshot</span>
                )}
                <button
                  onClick={handleStartRename}
                  className="opacity-0 group-hover/name:opacity-100 transition-opacity text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 p-0.5"
                  title="Rename snapshot"
                >
                  <Pencil className="w-3 h-3" />
                </button>
              </div>
            )}
            {/* Stats line */}
            <div className="text-xs text-gray-500 dark:text-gray-400 flex items-center gap-1.5">
              {sheet.total_trades} trade{sheet.total_trades !== 1 ? 's' : ''} · {fmtNotional(sheet.total_notional)}
              {recCount > 0 && (
                <span className="text-teal-600 dark:text-teal-400 flex items-center gap-0.5">
                  · <FileCheck className="h-3 w-3" /> {recCount} from recommendations
                </span>
              )}
            </div>
          </div>
        </div>
        <div className="flex items-center gap-2 flex-shrink-0 ml-3">
          <span className="text-xs text-gray-400 dark:text-gray-500">
            {formatDistanceToNow(new Date(sheet.created_at), { addSuffix: true })}
          </span>
        </div>
      </button>

      {/* Expanded trade details */}
      {expanded && variants.length > 0 && (
        <div className="border-t border-gray-200 dark:border-gray-700 px-3 py-2 bg-gray-50/50 dark:bg-gray-900/30">
          <table className="w-full">
            <thead>
              <tr className="text-[10px] font-medium uppercase tracking-wider text-gray-400 dark:text-gray-500">
                <th className="text-left py-1 pr-3">Action</th>
                <th className="text-left py-1 pr-3">Symbol</th>
                <th className="text-left py-1 pr-3">Sizing</th>
                <th className="text-right py-1 pr-3">Shrs</th>
                <th className="text-right py-1 pr-3">Weight</th>
                <th className="text-right py-1">Notional</th>
              </tr>
            </thead>
            <tbody>
              {variants.map((v: IntentVariant) => (
                <TradeRow key={v.id} variant={v} symbol={assetSymbolMap[v.asset_id] || 'Unknown'} />
              ))}
            </tbody>
            <tfoot>
              <tr className="border-t border-gray-200 dark:border-gray-700">
                <td colSpan={3} className="py-1.5 text-[11px] font-semibold text-gray-500 dark:text-gray-400">Total</td>
                <td className="py-1.5 text-[13px] font-mono font-semibold text-right text-gray-700 dark:text-gray-200">
                  {variants.reduce((sum: number, v: IntentVariant) => sum + (v.computed?.delta_shares ?? 0), 0).toLocaleString()}
                </td>
                <td className="py-1.5 text-[13px] font-mono font-semibold text-right text-gray-700 dark:text-gray-200">
                  {variants.reduce((sum: number, v: IntentVariant) => sum + (v.computed?.delta_weight ?? 0), 0).toFixed(2)}%
                </td>
                <td className="py-1.5 text-[13px] font-mono font-semibold text-right text-gray-700 dark:text-gray-200">
                  ${Math.abs(variants.reduce((sum: number, v: IntentVariant) => sum + (v.computed?.notional_value ?? 0), 0)).toLocaleString()}
                </td>
              </tr>
            </tfoot>
          </table>

          {/* Actions */}
          {variants.length > 0 && (
            <div className="flex items-center justify-between mt-3 pt-3 border-t border-gray-200 dark:border-gray-700">
              <div className="text-xs text-gray-500 dark:text-gray-400">
                Saved scenario
              </div>
              <div className="flex items-center gap-2">
                {/* Share snapshot */}
                {onShareSnapshot && (
                  <button
                    onClick={(e) => { e.stopPropagation(); onShareSnapshot(sheet) }}
                    title="Share this snapshot with a team member"
                    className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium rounded-md border border-gray-300 dark:border-gray-600 text-gray-500 dark:text-gray-400 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
                  >
                    <Send className="h-3.5 w-3.5" />
                    Share
                  </button>
                )}
                {/* Load into Trade Lab */}
                {onLoadSnapshot && (
                  <button
                    onClick={(e) => { e.stopPropagation(); onLoadSnapshot(sheet) }}
                    disabled={isLoadingSnapshot}
                    className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-md border border-primary-300 dark:border-primary-700 text-primary-700 dark:text-primary-400 hover:bg-primary-50 dark:hover:bg-primary-900/20 transition-colors disabled:opacity-50"
                  >
                    <RotateCcw className="h-3.5 w-3.5" />
                    {isLoadingSnapshot ? 'Loading...' : 'Load into Trade Lab'}
                  </button>
                )}
              </div>
            </div>
          )}
        </div>
      )}

      {expanded && variants.length === 0 && (
        <div className="border-t border-gray-200 dark:border-gray-700 px-3 py-4 text-center text-xs text-gray-400">
          No trade details available
        </div>
      )}
    </div>
  )
}

export function TradeSheetPanel({
  tradeSheets,
  assetSymbolMap = {},
  onLoadSnapshot,
  onShareSnapshot,
  isLoadingSnapshot,
  className = '',
}: TradeSheetPanelProps) {
  return (
    <div className={clsx('space-y-2', className)}>
      {tradeSheets.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-12 text-center">
          <Inbox className="w-10 h-10 text-gray-300 dark:text-gray-600 mb-3" />
          <p className="text-sm font-medium text-gray-500 dark:text-gray-400">No snapshots yet</p>
          <p className="text-xs text-gray-400 dark:text-gray-500 mt-1">Save a snapshot from the Simulation tab to share or revisit later</p>
        </div>
      ) : (
        tradeSheets.map(sheet => (
          <SheetListItem key={sheet.id} sheet={sheet} assetSymbolMap={assetSymbolMap} onLoadSnapshot={onLoadSnapshot} onShareSnapshot={onShareSnapshot} isLoadingSnapshot={isLoadingSnapshot} />
        ))
      )}
    </div>
  )
}

export default TradeSheetPanel
