-- ============================================================================
-- Fix phantom price-target notifications.
--
-- Background
-- ----------
-- `notify_price_target_changes` fired on every UPDATE without checking
-- whether `price` actually changed. The 20260425120000_org_scope_price_targets
-- migration ran a backfill UPDATE to populate organization_id, which touched
-- every price_targets row and triggered a flood of notifications with
-- old_price == new_price and changed_by = NULL.
--
-- Fixes
-- -----
-- 1. Only notify when a tracked field (price, timeframe, reasoning) actually
--    changed. Mirrors the guard already present in `track_price_target_changes`.
-- 2. Don't notify when the change is system-initiated (auth.uid() IS NULL),
--    e.g., a backfill, a scheduled job, or an admin SQL fix-up. Notifications
--    are for user actions; opaque system writes should not page coverage users.
-- 3. Carry the actual changed field type into the message so users see what
--    really changed, not just "the X case price target has been updated".
-- 4. Clean up the phantom notifications produced on 2026-04-25 22:05:41
--    where old_price == new_price.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.notify_price_target_changes()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
  asset_info  RECORD;
  changed_by  uuid;
  pretty_msg  text;
BEGIN
  -- Only act on UPDATEs.
  IF TG_OP <> 'UPDATE' THEN
    RETURN NEW;
  END IF;

  -- Skip system-initiated writes (migrations, scheduled jobs, admin SQL).
  -- A NULL auth.uid() means there's no user to attribute the change to,
  -- and notifying coverage users about an opaque server-side change is
  -- almost always noise.
  changed_by := auth.uid();
  IF changed_by IS NULL THEN
    RETURN NEW;
  END IF;

  -- Skip no-op UPDATEs across the fields users actually care about.
  IF OLD.price     IS NOT DISTINCT FROM NEW.price
     AND OLD.timeframe IS NOT DISTINCT FROM NEW.timeframe
     AND OLD.reasoning IS NOT DISTINCT FROM NEW.reasoning THEN
    RETURN NEW;
  END IF;

  SELECT symbol, company_name INTO asset_info
  FROM assets WHERE id = NEW.asset_id;

  -- Build a message describing what actually changed. Price is the
  -- meaningful change; reasoning/timeframe-only edits get a softer message.
  IF OLD.price IS DISTINCT FROM NEW.price THEN
    pretty_msg := format('The %s case price target changed from %s to %s',
                         NEW.type,
                         COALESCE(OLD.price::text, '—'),
                         COALESCE(NEW.price::text, '—'));
  ELSIF OLD.timeframe IS DISTINCT FROM NEW.timeframe THEN
    pretty_msg := format('The %s case timeframe was updated', NEW.type);
  ELSE
    pretty_msg := format('The %s case reasoning was updated', NEW.type);
  END IF;

  PERFORM create_asset_change_notification(
    NEW.asset_id,
    'price_target_change',
    'Price Target Updated: ' || asset_info.symbol,
    pretty_msg,
    jsonb_build_object(
      'price_target_type', NEW.type,
      'old_price',   OLD.price,
      'new_price',   NEW.price,
      'old_timeframe', OLD.timeframe,
      'new_timeframe', NEW.timeframe,
      'changed_by',  changed_by
    )
  );

  RETURN NEW;
END;
$function$;

-- ----------------------------------------------------------------------------
-- Clean up the phantom notifications generated by the org_scope_price_targets
-- backfill on 2026-04-25 22:05:41. Scope tightly: same exact timestamp,
-- price_target_change type, and old_price == new_price. Anything later
-- (real user activity) is left alone.
-- ----------------------------------------------------------------------------

DELETE FROM public.notifications
WHERE type = 'price_target_change'
  AND created_at = '2026-04-25 22:05:41.45002+00'
  AND (context_data->>'old_price') IS NOT DISTINCT FROM (context_data->>'new_price');
